# Generated by Django 4.0.4 on 2022-05-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('per_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_city', models.CharField(choices=[('New York', 'New York'), ('Atlanta', 'Atlanta'), ('Hong Kong', 'Hong Kong'), ('Los Angeles', 'Los Angeles'), ('Buenos Aires', 'Buenos Aires')], default='A', max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
