# Generated by Django 4.0.4 on 2022-05-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='consignee',
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.CharField(default='Consignee', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
