# Generated by Django 4.0.4 on 2022-05-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='storage_city',
            field=models.CharField(choices=[('New York', 'New York'), ('Atlanta', 'Atlanta'), ('Hong Kong', 'Hong Kong'), ('Los Angeles', 'Los Angeles'), ('Buenos Aires', 'Buenos Aires')], max_length=40),
        ),
    ]
