# Generated by Django 4.0.4 on 2022-05-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_inventory_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='date',
            new_name='shipment_date',
        ),
    ]
