# Generated by Django 4.0.4 on 2022-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_shipment_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='per_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
